export const SET_API_ERROR = 'API/SET_ERROR';
export const CLEAR_API_ERROR = 'API/CLEAR_ERROR';
export const INGREDIENTS_REQUESTED = 'API/INGREDIENTS_REQUESTED';
export const INGREDIENTS_RECEIVED = 'API/INGREDIENTS_RECEIVED';
export const INGREDIENTS_FAILED = 'API/INGREDIENTS_FAILED';
export const ORDER_PENDING = 'API/ORDER_PENDING';
export const ORDER_PLACED = 'API/ORDER_PLACED';
export const ORDER_FAILED = 'API/ORDER_FAILED';

export const ADD_BUN = 'CURRENT_BURGER/ADD_BUN';
export const ADD_OTHER = 'CURRENT_BURGER/ADD_OTHER';
export const REMOVE_INGREDIENT = 'CURRENT_BURGER/REMOVE_INGREDIENT';
export const RESET_BURGER = 'CURRENT_BURGER/RESET_BURGER';
export const CHANGE_ORDER = 'CURRENT_BURGER/CHANGE_ORDER';

export const SET_ORDER_ID = 'MODALS/SET_ORDER_ID';
export const RESET_ORDER_ID = 'MODALS/RESET_ORDER_ID';
export const SET_CURRENT_INGREDIENT = 'MODALS/SET_CURRENT_INGREDIENT';
export const RESET_CURRENT_INGREDIENT = 'MODALS/RESET_CURRENT_INGREDIENT';

export const SET_IS_DRAGGING_INGREDIENT = 'DRAG/SET_IS_DRAGGING_INGREDIENT';